name: merge-test-env-check
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing environment check
        run: |
          echo "Checking testing environment.. OK"
